# Generated by Django 2.0.5 on 2018-05-11 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='attrs',
        ),
    ]
