# Generated by Django 2.0.5 on 2018-05-09 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='username',
            new_name='userid',
        ),
    ]
