# Generated by Django 2.0.5 on 2018-05-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20180509_0200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='song_name',
        ),
        migrations.AddField(
            model_name='song',
            name='playlist_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.Playlist'),
        ),
    ]
