# Generated by Django 2.0.5 on 2018-05-09 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20180509_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='username',
            new_name='user',
        ),
    ]
